In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])
print(a)

[2 3 4]


In [3]:
b = np.array([
    [0.1,0.2,0.3,0.4],[0.5,0.6,0.7,0.8]
    ])
print(b)

[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]


In [4]:
c = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]
])
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
c.ndim

3

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 4)

In [10]:
c.shape

(2, 3, 3)

In [11]:
a.dtype

dtype('int64')

In [12]:
d = np.array([7,8,6], dtype = 'int16')

In [13]:
d.dtype

dtype('int16')

In [14]:
d.itemsize

2

In [15]:
a.itemsize

8

In [16]:
a.size

3

In [17]:
totalsize = a.size * a.itemsize
print(totalsize)

24


In [18]:
a.nbytes

24

ACCESS / Change

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a[1,5]

np.int64(13)

In [21]:
a[1,-5]

np.int64(10)

In [22]:
a[1,:] #fetching row

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
a[:,1] # fetching Column

array([2, 9])

In [24]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [25]:
a[1,0:-1:2] #fancy indexing choosing with jump

array([ 8, 10, 12])

In [26]:
a[0,4] = 11  #changing specific element

In [27]:
a

array([[ 1,  2,  3,  4, 11,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [28]:
a[:,1] = 5

In [29]:
a

array([[ 1,  5,  3,  4, 11,  6,  7],
       [ 8,  5, 10, 11, 12, 13, 14]])

In [30]:
a[:,1] = [1,2] #changing row

In [31]:
a

array([[ 1,  1,  3,  4, 11,  6,  7],
       [ 8,  2, 10, 11, 12, 13, 14]])

In [32]:
b = np.array([
    [[1,2], [3,4]],
    [[5,6],[7,8]]
    ])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
b[1,0,1]  #fetching from 3d array

np.int64(6)

In [35]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [36]:
b[:,0,:] = [[7,8],[9,10]] #changing values

In [37]:
b

array([[[ 7,  8],
        [ 3,  4]],

       [[ 9, 10],
        [ 7,  8]]])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.full((3,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [43]:
np.random.rand(4,2)

array([[0.18829425, 0.17893335],
       [0.45151043, 0.22959541],
       [0.04920282, 0.0320286 ],
       [0.39173104, 0.94500124]])

In [44]:
np.random.random_sample(a.shape)

array([[0.19723567, 0.76888844, 0.82082193, 0.71806809, 0.46678325,
        0.5337836 , 0.20466084],
       [0.6595051 , 0.02788747, 0.26465082, 0.17925546, 0.94202328,
        0.65855213, 0.18583041]])

In [48]:
np.random.random_integers(6, size = (4,2))

/tmp/ipython-input-2016111745.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  np.random.random_integers(6, size = (4,2))


array([[5, 2],
       [6, 1],
       [6, 1],
       [1, 2]])

In [49]:
np.random.randint(4, size = (3,3))

array([[2, 0, 3],
       [1, 0, 1],
       [2, 2, 3]])

In [70]:
np.random.randint(1, size = (3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
arr = np.array([1,2,3])

[1 1 1 2 2 2 3 3 3]


In [53]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [71]:
a = np.random.randint(1, size = (5,5))
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

array([[4, 1, 3, 3, 8],
       [1, 5, 8, 8, 6],
       [1, 2, 1, 4, 5],
       [2, 3, 7, 8, 7],
       [5, 2, 3, 2, 8]])

In [72]:
a[0,:] = 1
a[:,0] = 1
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [73]:
a[:,-1] = 1
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

In [74]:
a[-1,:] = 1
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [75]:
a[2,2] = 9

In [76]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Mathmetical operations can be done
Moving on to linear algebra stuff

In [77]:
a = np.ones((2,3))
b = np.full((3,2),2)

In [78]:
a,b

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [79]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [83]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.linalg.det(c)

np.float64(1.0)

Statistics

In [85]:
a = np.array([[1,2,3],[4,5,6]])

In [86]:
np.max(a)

np.int64(6)

In [87]:
np.min(a)

np.int64(1)

In [90]:
np.max(a, axis = 1)

array([3, 6])

In [91]:
np.sum(a)

np.int64(21)

In [92]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [93]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
arr.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

Vertical Stack

In [95]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [99]:
file_data = np.genfromtxt('data.txt', delimiter=',')

In [101]:
file_data = file_data.astype('int32')
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [102]:
file_data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [103]:
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [104]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,-1]]

array([2, 3, 9])

In [105]:
np.any(file_data > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [106]:
((file_data > 50) & (file_data < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [107]:
temp = np.array([22.5, 23.0, 21.0, 20.5, 24.0, 25.5, 23.5])

In [108]:
temp.min()

np.float64(20.5)

In [109]:
temp.max()

np.float64(25.5)

In [112]:
temp.mean()

np.float64(22.857142857142858)

In [113]:
np.mean(temp)

np.float64(22.857142857142858)

In [114]:
fh = (temp * 9/5) + 32

In [115]:
fh

array([72.5, 73.4, 69.8, 68.9, 75.2, 77.9, 74.3])

In [118]:
temp[(temp > 23)]

array([24. , 25.5, 23.5])

In [119]:
a = np.array([10, 20, 30, 40])
a[1:3]

array([20, 30])

In [120]:
x = np.array([[1, 2], [3, 4]])
x.reshape((4,))

array([1, 2, 3, 4])

In [121]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [122]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

np.int64(32)

In [123]:
np.arange(1,19,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])